### ISSUE TITLE
Provide pure Python alternative

### ISSUE THREAD

**Issue by sametmax** [SerialDev/Pyo3_Running_Stats#1]
Hi,

It would be nice to have a pure Python version of the algo, so that we can use it in the cases where:

- we don't have a compiler
- we use an alternative python interpreter (pypy, jython, micropython, iron python)
- we are in a dev mode 
- we just do a simple script to pass around
- we want to compile it with numba or 
- we try to learn from the algo and only know Python

It would also mean more contributions. E.G: people could PR unit test or setup.py files so that you can pip install it.

**Comment by SerialDev** [comment]
I will add a pure Python 3+ implementation for it, however I think it would be good to look into [`setuptools-rust](https://github.com/PyO3/setuptools-rust) to make pip install a breeze. but I do agree on the pypy/jython/etc support being useful.

**Comment by SerialDev** [comment]
Pure python alternative under /ref
